### ISSUE TITLE
Outline legal fillings needed and timeline

### ISSUE THREAD

**Issue by dlindahl** [techramento/techramento.github.io#5]
TO-DO:
- [x] Check name availability with Secretary of State
- [x] Reserve corporate name    Secretary of State
- [x] Prepare Articles of Incorporation
- [x] File Articles of Incorporation with Secretary of State (3-4 weeks) #14 
- [x] Apply for IRS Employee Identification Number #15 
- [x] Open Bank Account #16
- [x] Generate Bylaws
- [x] File Statement of Information with Secretary of State #21 
- [x] Generate and file Federal Exemption Application with Internal Revenue Service (2-4 months) #22 
- [x] Register with the Attorney General's Registry of Charitable Trusts #23
- [x] Understand and comply with the Attorney General California Nonprofit Integrity Act of 2004 (ongoing) #25
- [x] Prepare and file State Exemption Application with Franchise Tax Board (#27)

For a description of each step, check out the [Wiki: Basic Steps for Starting a California Nonprofit](https://github.com/techramento/techramento.github.io/wiki/Basic-Steps-for-Starting-a-California-Nonprofit).

**Comment by dlindahl** [comment]
This has been researched but needs to be codified

**Comment by roughani** [comment]
TO-DO:

- [x] Check name availability with Secretary of State
- [x] Reserve corporate name	Secretary of State
- [ ] Prepare Articles of Incorporation
- [ ] File Articles of Incorporation with Secretary of State (3-4 weeks)
- [ ] Apply for IRS Employee Identification Number 
- [ ] Generate Bylaws
- [ ] File Statement of Information with Secretary of State 
- [ ] Prepare and file State Exemption Application with Franchise Tax Board (Pro Tip: We can obtain IRS exemption prior to state exemption to expedite approval of state exemption)
- [ ] Generate and file Federal Exemption Application with Internal Revenue Service (2-4 months)
- [ ] Register with the Attorney General's Registry of Charitable Trusts
- [ ] Understand and comply with the Attorney General California Nonprofit Integrity Act of 2004 (ongoing)

For a description of each step, check out the [Wiki: Basic Steps for Starting a California Nonprofit] (https://github.com/techramento/techramento.github.io/wiki/Basic-Steps-for-Starting-a-California-Nonprofit).

**Comment by dlindahl** [comment]
Costs of creating the legal entity are captured in Issue #4

**Comment by dlindahl** [comment]
Tabled to next meeting (in order to be tabled to the next meeting :smile:)

**Comment by dlindahl** [comment]
Linked to two new issues (#23 and #25) for more detailed tracking

Will address #22 at end of Apr 10 meeting to fill out the form.

**Comment by roughani** [comment]
Updated the this issue's checklist to clarify that we still need to receive tax exempt status from the state (Franchise Tax Board). But it's a really short form and we just need to send them our IRS Determination letter. See #27. 

FWIW, it's our last step!

**Comment by dlindahl** [comment]
Haven't heard back from the state yet. I will ping them and see what the deal is.
